"""
given two strings s and t which consist of only two
lowercase letters
string t is generated by random shuffling string s and then
add one more letter at a random position. find the letter that was added in
it
for example :
input :
s = "abcd"  t是从
t = "abecd"
output: "e"

explanation:
'e' is the letter that was added
 We use the characteristic equation of XOR.
A xor B xor C = A xor C xor B
If A == C, then A xor C = 0
and then, B xor 0 =  B
"""
def find_difference(s, t):
  ret = 0
  for ch in s + t:
      #ord(ch) return an integer representing the unicode code point of that character

      ret = ret ^ ord(ch)
      #chr(i) return the string representing a character whose unicode points is the integer i

  return chr(ret)

if __name__ == '__main__':
    print(find_difference("abcd","cedba"))
    s = "abcd"
    b = "abdce"
    print(s+b)